version: '3'
services:
  app:
    # Build from dockerfile.
    build: .
    # Specify a container name.
    container_name: ChatBot
    # Expose ports container : host
    ports:
      - 7860:7860
    # Command to start the server.
    command: python chatbot.py