version: '3'
services:
  app:
    image: chatbot_dev
    # Build from dockerfile.
    build: .
    # Specify a container name.
    container_name: ChatBotDev
    # Expose ports container : host
    ports:
      - 7676:7676
    # Command to start the server.
    command: python chatbot.py